export const publicPaths = [
    '/login',
    '/about',
    '/register',
    '/forgot-password',
    '/reset-password',
    '/callback',
    '/privacy-policy',
    '/user-agreement',
    '/privacy',
    '/terms',
    '/posts',
    '/categories',
    '/tags',
    '/archives',
]
